service: aws-demo

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-north-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /githubmonitor
          method: post
